"""Generate MANIFEST.md: every manuscript statistic mapped back to its source.

Parses the assignments in export_numbers.build() so the map cannot drift from the code,
and joins each macro to the value actually written into manuscript/numbers.tex.
"""
import inspect
import os
import re

import export_numbers

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BLOCKS = {
    "hl": ("headline", "analyze.py:headline"),
    "a1": ("a1_confidence_semantics", "analyze.py:a1_confidence_semantics"),
    "a2": ("a2_calibration", "analyze.py:a2_calibration"),
    "a3": ("a3_conditional_error", "analyze.py:a3_conditional_error"),
    "a4": ("a4_selective_prediction", "analyze.py:a4_selective_prediction"),
    "a5": ("a5_circular", "analyze.py:a5_circular"),
    "cy": ("a5_circular.cyber", "analyze.py:a5_circular"),
    "bi": ("a5_circular.bio", "analyze.py:a5_circular"),
    "ndc": ("a5_circular.cyber.nondeterminism", "analyze.py:_nondeterminism"),
    "ndb": ("a5_circular.bio.nondeterminism", "analyze.py:_nondeterminism"),
    "a6": ("a6_cascade", "analyze.py:a6_cascade"),
    "a7": ("a7_breakeven", "analyze.py:a7_breakeven"),
    "a8": ("a8_position_bias", "analyze.py:a8_position_bias"),
    "pb": ("a8_position_bias.per_dataset", "analyze.py:_pos_test"),
    "st": ("a8_position_bias.stratified", "analyze.py:_pos_test"),
    "cb": ("a8_position_bias.chance_baselines", "analyze.py:a8_position_bias"),
    "a9": ("a9_sensitivity", "analyze.py:a9_sensitivity"),
    "q": ("a9_sensitivity.quantisation", "analyze.py:a9_sensitivity"),
    "a10": ("a10_cost", "analyze.py:a10_cost"),
    "e": ("a3_conditional_error.per_dataset", "analyze.py:a3_conditional_error"),
    "rc": ("a4_selective_prediction.risk_coverage", "analyze.py:a4_selective_prediction"),
    "c20": ("a6_cascade.cyber.confidence_router", "analyze.py:a6_cascade"),
    "c40": ("a6_cascade.cyber.confidence_router", "analyze.py:a6_cascade"),
    "r40": ("a6_cascade.cyber.random_router", "analyze.py:a6_cascade"),
    "t": ("a3_conditional_error.tests", "analyze.py:a3_conditional_error"),
}

RAW_SOURCES = """Raw inputs
----------
`raw/{bio,chem,cyber,bio-robust}.jsonl`  single-pass WMDP decision records
`raw/labbench-*.jsonl`                   single-pass LAB-Bench decision records (6 subtasks)
`raw/perm_{bio,cyber}.json`              all 4 cyclic rotations per item, mapped to
                                         original option indices
"""


def main():
    src = inspect.getsource(export_numbers.build)
    values = {}
    with open(os.path.join(ROOT, "..", "manuscript", "numbers.tex")) as fh:
        for line in fh:
            m = re.match(r"\\newcommand\{\\(stat[A-Za-z]+)\}\{(.*)\}$", line.strip())
            if m:
                values[m.group(1)] = m.group(2)

    rows, section = [], "general"
    for line in src.splitlines():
        c = re.match(r"\s*#\s*-*\s*(.+)", line)
        if c and "---" in line:
            section = c.group(1).strip("- ")
            continue
        m = re.search(r'M\[(?:f?)"(stat[A-Za-z{}a-z]*)"\]\s*=\s*(.*)', line)
        if not m:
            continue
        name, expr = m.group(1), m.group(2)
        if "{tag}" in name:           # emitted by a loop over datasets
            matching = sorted(k for k in values if k.startswith(name.split("{")[0]))
        else:
            matching = [name] if name in values else []
        blk = next((BLOCKS[v][0] for v in re.findall(r"\b([a-z0-9]+)\[", expr)
                    if v in BLOCKS), "")
        fn = next((BLOCKS[v][1] for v in re.findall(r"\b([a-z0-9]+)\[", expr)
                   if v in BLOCKS), "")
        for nm in matching:
            rows.append((section, nm, values.get(nm, "?"), blk, fn))

    seen, out = set(), []
    for r in rows:
        if r[1] in seen:
            continue
        seen.add(r[1])
        out.append(r)
    missing = sorted(set(values) - seen)

    lines = ["# MANIFEST", "",
             "Every statistic in the manuscript, the value it renders to, and the code",
             "and data it derives from. Generated by `code/make_manifest.py`; do not edit.",
             "", "```", RAW_SOURCES.strip(), "```", "",
             f"{len(values)} macros defined in `manuscript/numbers.tex`.", "",
             "| macro | value | stats.json block | produced by |",
             "|---|---|---|---|"]
    cur = None
    for section, name, val, blk, fn in out:
        if section != cur:
            cur = section
            lines.append(f"| **{section}** | | | |")
        safe = val.replace("|", "\\|").replace("\\%", "%")
        lines.append(f"| `\\{name}` | {safe} | `{blk}` | `{fn}` |")
    if missing:
        lines += ["", "Unmapped (defined but not traced to a block): "
                  + ", ".join(f"`\\{m}`" for m in missing)]
    path = os.path.join(ROOT, "MANIFEST.md")
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {path}: {len(out)} mapped, {len(missing)} unmapped")


if __name__ == "__main__":
    main()
